<?php
/**
 * DirectDebitApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Alexasomba\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paystack
 *
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: techsupport@paystack.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Alexasomba\Paystack\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Alexasomba\Paystack\ApiException;
use Alexasomba\Paystack\Configuration;
use Alexasomba\Paystack\FormDataProcessor;
use Alexasomba\Paystack\HeaderSelector;
use Alexasomba\Paystack\ObjectSerializer;

/**
 * DirectDebitApi Class Doc Comment
 *
 * @category Class
 * @package  Alexasomba\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DirectDebitApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'listMandateAuthorizations' => [
            'application/json',
        ],
        'triggerActivationCharge' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation listMandateAuthorizations
     *
     * List Mandate Authorizations
     *
     * @param  string|null $cursor The cursor value of the next set of authorizations to fetch. You can get this from the meta object of the response (optional)
     * @param  string|null $status Filter by the authorization status (optional)
     * @param  int|null $perPage The number of authorizations to fetch per request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMandateAuthorizations'] to see the possible values for this operation
     *
     * @throws \Alexasomba\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Alexasomba\Paystack\Model\CustomerFetchMandateAuthorizationsResponse|\Alexasomba\Paystack\Model\Error
     */
    public function listMandateAuthorizations($cursor = null, $status = null, $perPage = null, string $contentType = self::contentTypes['listMandateAuthorizations'][0])
    {
        list($response) = $this->listMandateAuthorizationsWithHttpInfo($cursor, $status, $perPage, $contentType);
        return $response;
    }

    /**
     * Operation listMandateAuthorizationsWithHttpInfo
     *
     * List Mandate Authorizations
     *
     * @param  string|null $cursor The cursor value of the next set of authorizations to fetch. You can get this from the meta object of the response (optional)
     * @param  string|null $status Filter by the authorization status (optional)
     * @param  int|null $perPage The number of authorizations to fetch per request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMandateAuthorizations'] to see the possible values for this operation
     *
     * @throws \Alexasomba\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Alexasomba\Paystack\Model\CustomerFetchMandateAuthorizationsResponse|\Alexasomba\Paystack\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function listMandateAuthorizationsWithHttpInfo($cursor = null, $status = null, $perPage = null, string $contentType = self::contentTypes['listMandateAuthorizations'][0])
    {
        $request = $this->listMandateAuthorizationsRequest($cursor, $status, $perPage, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\Paystack\Model\CustomerFetchMandateAuthorizationsResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\Paystack\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Alexasomba\Paystack\Model\CustomerFetchMandateAuthorizationsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\Paystack\Model\CustomerFetchMandateAuthorizationsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\Paystack\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listMandateAuthorizationsAsync
     *
     * List Mandate Authorizations
     *
     * @param  string|null $cursor The cursor value of the next set of authorizations to fetch. You can get this from the meta object of the response (optional)
     * @param  string|null $status Filter by the authorization status (optional)
     * @param  int|null $perPage The number of authorizations to fetch per request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMandateAuthorizations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listMandateAuthorizationsAsync($cursor = null, $status = null, $perPage = null, string $contentType = self::contentTypes['listMandateAuthorizations'][0])
    {
        return $this->listMandateAuthorizationsAsyncWithHttpInfo($cursor, $status, $perPage, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listMandateAuthorizationsAsyncWithHttpInfo
     *
     * List Mandate Authorizations
     *
     * @param  string|null $cursor The cursor value of the next set of authorizations to fetch. You can get this from the meta object of the response (optional)
     * @param  string|null $status Filter by the authorization status (optional)
     * @param  int|null $perPage The number of authorizations to fetch per request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMandateAuthorizations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listMandateAuthorizationsAsyncWithHttpInfo($cursor = null, $status = null, $perPage = null, string $contentType = self::contentTypes['listMandateAuthorizations'][0])
    {
        $returnType = '\Alexasomba\Paystack\Model\CustomerFetchMandateAuthorizationsResponse';
        $request = $this->listMandateAuthorizationsRequest($cursor, $status, $perPage, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listMandateAuthorizations'
     *
     * @param  string|null $cursor The cursor value of the next set of authorizations to fetch. You can get this from the meta object of the response (optional)
     * @param  string|null $status Filter by the authorization status (optional)
     * @param  int|null $perPage The number of authorizations to fetch per request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listMandateAuthorizations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listMandateAuthorizationsRequest($cursor = null, $status = null, $perPage = null, string $contentType = self::contentTypes['listMandateAuthorizations'][0])
    {





        $resourcePath = '/directdebit/mandate-authorizations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $perPage,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation triggerActivationCharge
     *
     * Trigger Activation Charge
     *
     * @param  \Alexasomba\Paystack\Model\DirectDebitActivationChargeRequest $directDebitActivationChargeRequest directDebitActivationChargeRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['triggerActivationCharge'] to see the possible values for this operation
     *
     * @throws \Alexasomba\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Alexasomba\Paystack\Model\DirectDebitActivationChargeResponse|\Alexasomba\Paystack\Model\Error
     */
    public function triggerActivationCharge($directDebitActivationChargeRequest, string $contentType = self::contentTypes['triggerActivationCharge'][0])
    {
        list($response) = $this->triggerActivationChargeWithHttpInfo($directDebitActivationChargeRequest, $contentType);
        return $response;
    }

    /**
     * Operation triggerActivationChargeWithHttpInfo
     *
     * Trigger Activation Charge
     *
     * @param  \Alexasomba\Paystack\Model\DirectDebitActivationChargeRequest $directDebitActivationChargeRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['triggerActivationCharge'] to see the possible values for this operation
     *
     * @throws \Alexasomba\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Alexasomba\Paystack\Model\DirectDebitActivationChargeResponse|\Alexasomba\Paystack\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function triggerActivationChargeWithHttpInfo($directDebitActivationChargeRequest, string $contentType = self::contentTypes['triggerActivationCharge'][0])
    {
        $request = $this->triggerActivationChargeRequest($directDebitActivationChargeRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\Paystack\Model\DirectDebitActivationChargeResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\Paystack\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Alexasomba\Paystack\Model\DirectDebitActivationChargeResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\Paystack\Model\DirectDebitActivationChargeResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\Paystack\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation triggerActivationChargeAsync
     *
     * Trigger Activation Charge
     *
     * @param  \Alexasomba\Paystack\Model\DirectDebitActivationChargeRequest $directDebitActivationChargeRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['triggerActivationCharge'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function triggerActivationChargeAsync($directDebitActivationChargeRequest, string $contentType = self::contentTypes['triggerActivationCharge'][0])
    {
        return $this->triggerActivationChargeAsyncWithHttpInfo($directDebitActivationChargeRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation triggerActivationChargeAsyncWithHttpInfo
     *
     * Trigger Activation Charge
     *
     * @param  \Alexasomba\Paystack\Model\DirectDebitActivationChargeRequest $directDebitActivationChargeRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['triggerActivationCharge'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function triggerActivationChargeAsyncWithHttpInfo($directDebitActivationChargeRequest, string $contentType = self::contentTypes['triggerActivationCharge'][0])
    {
        $returnType = '\Alexasomba\Paystack\Model\DirectDebitActivationChargeResponse';
        $request = $this->triggerActivationChargeRequest($directDebitActivationChargeRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'triggerActivationCharge'
     *
     * @param  \Alexasomba\Paystack\Model\DirectDebitActivationChargeRequest $directDebitActivationChargeRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['triggerActivationCharge'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function triggerActivationChargeRequest($directDebitActivationChargeRequest, string $contentType = self::contentTypes['triggerActivationCharge'][0])
    {

        // verify the required parameter 'directDebitActivationChargeRequest' is set
        if ($directDebitActivationChargeRequest === null || (is_array($directDebitActivationChargeRequest) && count($directDebitActivationChargeRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $directDebitActivationChargeRequest when calling triggerActivationCharge'
            );
        }


        $resourcePath = '/directdebit/activation-charge';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($directDebitActivationChargeRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($directDebitActivationChargeRequest));
            } else {
                $httpBody = $directDebitActivationChargeRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
