<?php
/**
 * TransferRecipientApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Alexasomba\\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paystack
 *
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: techsupport@paystack.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Alexasomba\\Paystack\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Alexasomba\\Paystack\ApiException;
use Alexasomba\\Paystack\Configuration;
use Alexasomba\\Paystack\FormDataProcessor;
use Alexasomba\\Paystack\HeaderSelector;
use Alexasomba\\Paystack\ObjectSerializer;

/**
 * TransferRecipientApi Class Doc Comment
 *
 * @category Class
 * @package  Alexasomba\\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransferRecipientApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'transferrecipientBulk' => [
            'application/json',
            'application/x-www-form-urlencoded',
        ],
        'transferrecipientCreate' => [
            'application/json',
            'application/x-www-form-urlencoded',
        ],
        'transferrecipientDelete' => [
            'application/json',
        ],
        'transferrecipientFetch' => [
            'application/json',
        ],
        'transferrecipientList' => [
            'application/json',
        ],
        'transferrecipientUpdate' => [
            'application/json',
            'application/x-www-form-urlencoded',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation transferrecipientBulk
     *
     * Bulk Create Transfer Recipient
     *
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientBulk|null $transfer_recipient_bulk transfer_recipient_bulk (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientBulk'] to see the possible values for this operation
     *
     * @throws \Alexasomba\\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Alexasomba\\Paystack\Model\TransferRecipientBulkCreateResponse|\Alexasomba\\Paystack\Model\Error
     */
    public function transferrecipientBulk($transfer_recipient_bulk = null, string $contentType = self::contentTypes['transferrecipientBulk'][0])
    {
        list($response) = $this->transferrecipientBulkWithHttpInfo($transfer_recipient_bulk, $contentType);
        return $response;
    }

    /**
     * Operation transferrecipientBulkWithHttpInfo
     *
     * Bulk Create Transfer Recipient
     *
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientBulk|null $transfer_recipient_bulk (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientBulk'] to see the possible values for this operation
     *
     * @throws \Alexasomba\\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Alexasomba\\Paystack\Model\TransferRecipientBulkCreateResponse|\Alexasomba\\Paystack\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function transferrecipientBulkWithHttpInfo($transfer_recipient_bulk = null, string $contentType = self::contentTypes['transferrecipientBulk'][0])
    {
        $request = $this->transferrecipientBulkRequest($transfer_recipient_bulk, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\TransferRecipientBulkCreateResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Alexasomba\\Paystack\Model\TransferRecipientBulkCreateResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\TransferRecipientBulkCreateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation transferrecipientBulkAsync
     *
     * Bulk Create Transfer Recipient
     *
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientBulk|null $transfer_recipient_bulk (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientBulk'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferrecipientBulkAsync($transfer_recipient_bulk = null, string $contentType = self::contentTypes['transferrecipientBulk'][0])
    {
        return $this->transferrecipientBulkAsyncWithHttpInfo($transfer_recipient_bulk, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation transferrecipientBulkAsyncWithHttpInfo
     *
     * Bulk Create Transfer Recipient
     *
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientBulk|null $transfer_recipient_bulk (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientBulk'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferrecipientBulkAsyncWithHttpInfo($transfer_recipient_bulk = null, string $contentType = self::contentTypes['transferrecipientBulk'][0])
    {
        $returnType = '\Alexasomba\\Paystack\Model\TransferRecipientBulkCreateResponse';
        $request = $this->transferrecipientBulkRequest($transfer_recipient_bulk, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'transferrecipientBulk'
     *
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientBulk|null $transfer_recipient_bulk (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientBulk'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function transferrecipientBulkRequest($transfer_recipient_bulk = null, string $contentType = self::contentTypes['transferrecipientBulk'][0])
    {



        $resourcePath = '/transferrecipient/bulk';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($transfer_recipient_bulk)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($transfer_recipient_bulk));
            } else {
                $httpBody = $transfer_recipient_bulk;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation transferrecipientCreate
     *
     * Create Transfer Recipient
     *
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientCreate|null $transfer_recipient_create transfer_recipient_create (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientCreate'] to see the possible values for this operation
     *
     * @throws \Alexasomba\\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Alexasomba\\Paystack\Model\TransferRecipientCreateResponse|\Alexasomba\\Paystack\Model\Error
     */
    public function transferrecipientCreate($transfer_recipient_create = null, string $contentType = self::contentTypes['transferrecipientCreate'][0])
    {
        list($response) = $this->transferrecipientCreateWithHttpInfo($transfer_recipient_create, $contentType);
        return $response;
    }

    /**
     * Operation transferrecipientCreateWithHttpInfo
     *
     * Create Transfer Recipient
     *
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientCreate|null $transfer_recipient_create (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientCreate'] to see the possible values for this operation
     *
     * @throws \Alexasomba\\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Alexasomba\\Paystack\Model\TransferRecipientCreateResponse|\Alexasomba\\Paystack\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function transferrecipientCreateWithHttpInfo($transfer_recipient_create = null, string $contentType = self::contentTypes['transferrecipientCreate'][0])
    {
        $request = $this->transferrecipientCreateRequest($transfer_recipient_create, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\TransferRecipientCreateResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Alexasomba\\Paystack\Model\TransferRecipientCreateResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\TransferRecipientCreateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation transferrecipientCreateAsync
     *
     * Create Transfer Recipient
     *
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientCreate|null $transfer_recipient_create (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferrecipientCreateAsync($transfer_recipient_create = null, string $contentType = self::contentTypes['transferrecipientCreate'][0])
    {
        return $this->transferrecipientCreateAsyncWithHttpInfo($transfer_recipient_create, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation transferrecipientCreateAsyncWithHttpInfo
     *
     * Create Transfer Recipient
     *
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientCreate|null $transfer_recipient_create (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferrecipientCreateAsyncWithHttpInfo($transfer_recipient_create = null, string $contentType = self::contentTypes['transferrecipientCreate'][0])
    {
        $returnType = '\Alexasomba\\Paystack\Model\TransferRecipientCreateResponse';
        $request = $this->transferrecipientCreateRequest($transfer_recipient_create, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'transferrecipientCreate'
     *
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientCreate|null $transfer_recipient_create (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function transferrecipientCreateRequest($transfer_recipient_create = null, string $contentType = self::contentTypes['transferrecipientCreate'][0])
    {



        $resourcePath = '/transferrecipient';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($transfer_recipient_create)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($transfer_recipient_create));
            } else {
                $httpBody = $transfer_recipient_create;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation transferrecipientDelete
     *
     * Delete Transfer Recipient
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientDelete'] to see the possible values for this operation
     *
     * @throws \Alexasomba\\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Alexasomba\\Paystack\Model\TransferRecipientDeleteResponse|\Alexasomba\\Paystack\Model\Error|\Alexasomba\\Paystack\Model\Error
     */
    public function transferrecipientDelete($id_or_code, string $contentType = self::contentTypes['transferrecipientDelete'][0])
    {
        list($response) = $this->transferrecipientDeleteWithHttpInfo($id_or_code, $contentType);
        return $response;
    }

    /**
     * Operation transferrecipientDeleteWithHttpInfo
     *
     * Delete Transfer Recipient
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientDelete'] to see the possible values for this operation
     *
     * @throws \Alexasomba\\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Alexasomba\\Paystack\Model\TransferRecipientDeleteResponse|\Alexasomba\\Paystack\Model\Error|\Alexasomba\\Paystack\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function transferrecipientDeleteWithHttpInfo($id_or_code, string $contentType = self::contentTypes['transferrecipientDelete'][0])
    {
        $request = $this->transferrecipientDeleteRequest($id_or_code, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\TransferRecipientDeleteResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\Error',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Alexasomba\\Paystack\Model\TransferRecipientDeleteResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\TransferRecipientDeleteResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation transferrecipientDeleteAsync
     *
     * Delete Transfer Recipient
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferrecipientDeleteAsync($id_or_code, string $contentType = self::contentTypes['transferrecipientDelete'][0])
    {
        return $this->transferrecipientDeleteAsyncWithHttpInfo($id_or_code, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation transferrecipientDeleteAsyncWithHttpInfo
     *
     * Delete Transfer Recipient
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferrecipientDeleteAsyncWithHttpInfo($id_or_code, string $contentType = self::contentTypes['transferrecipientDelete'][0])
    {
        $returnType = '\Alexasomba\\Paystack\Model\TransferRecipientDeleteResponse';
        $request = $this->transferrecipientDeleteRequest($id_or_code, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'transferrecipientDelete'
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function transferrecipientDeleteRequest($id_or_code, string $contentType = self::contentTypes['transferrecipientDelete'][0])
    {

        // verify the required parameter 'id_or_code' is set
        if ($id_or_code === null || (is_array($id_or_code) && count($id_or_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_or_code when calling transferrecipientDelete'
            );
        }


        $resourcePath = '/transferrecipient/{id_or_code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id_or_code !== null) {
            $resourcePath = str_replace(
                '{' . 'id_or_code' . '}',
                ObjectSerializer::toPathValue($id_or_code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation transferrecipientFetch
     *
     * Fetch Transfer recipient
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientFetch'] to see the possible values for this operation
     *
     * @throws \Alexasomba\\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Alexasomba\\Paystack\Model\TransferRecipientFetchResponse|\Alexasomba\\Paystack\Model\Error|\Alexasomba\\Paystack\Model\Error
     */
    public function transferrecipientFetch($id_or_code, string $contentType = self::contentTypes['transferrecipientFetch'][0])
    {
        list($response) = $this->transferrecipientFetchWithHttpInfo($id_or_code, $contentType);
        return $response;
    }

    /**
     * Operation transferrecipientFetchWithHttpInfo
     *
     * Fetch Transfer recipient
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientFetch'] to see the possible values for this operation
     *
     * @throws \Alexasomba\\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Alexasomba\\Paystack\Model\TransferRecipientFetchResponse|\Alexasomba\\Paystack\Model\Error|\Alexasomba\\Paystack\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function transferrecipientFetchWithHttpInfo($id_or_code, string $contentType = self::contentTypes['transferrecipientFetch'][0])
    {
        $request = $this->transferrecipientFetchRequest($id_or_code, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\TransferRecipientFetchResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\Error',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Alexasomba\\Paystack\Model\TransferRecipientFetchResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\TransferRecipientFetchResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation transferrecipientFetchAsync
     *
     * Fetch Transfer recipient
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientFetch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferrecipientFetchAsync($id_or_code, string $contentType = self::contentTypes['transferrecipientFetch'][0])
    {
        return $this->transferrecipientFetchAsyncWithHttpInfo($id_or_code, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation transferrecipientFetchAsyncWithHttpInfo
     *
     * Fetch Transfer recipient
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientFetch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferrecipientFetchAsyncWithHttpInfo($id_or_code, string $contentType = self::contentTypes['transferrecipientFetch'][0])
    {
        $returnType = '\Alexasomba\\Paystack\Model\TransferRecipientFetchResponse';
        $request = $this->transferrecipientFetchRequest($id_or_code, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'transferrecipientFetch'
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientFetch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function transferrecipientFetchRequest($id_or_code, string $contentType = self::contentTypes['transferrecipientFetch'][0])
    {

        // verify the required parameter 'id_or_code' is set
        if ($id_or_code === null || (is_array($id_or_code) && count($id_or_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_or_code when calling transferrecipientFetch'
            );
        }


        $resourcePath = '/transferrecipient/{id_or_code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id_or_code !== null) {
            $resourcePath = str_replace(
                '{' . 'id_or_code' . '}',
                ObjectSerializer::toPathValue($id_or_code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation transferrecipientList
     *
     * List Transfer Recipients
     *
     * @param  int|null $per_page Specify how many records you want to retrieve per page. If not specified, we use a default value of 50. (optional)
     * @param  int|null $page Specify exactly what page you want to retrieve. If not specified, we use a default value of 1. (optional)
     * @param  \DateTime|null $from A timestamp from which to start listing transfer recipients e.g. 2016-09-24T00:00:05.000Z, 2016-09-21 (optional)
     * @param  \DateTime|null $to A timestamp at which to stop listing transfer recipients e.g. 2016-09-24T00:00:05.000Z, 2016-09-21 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientList'] to see the possible values for this operation
     *
     * @throws \Alexasomba\\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Alexasomba\\Paystack\Model\TransferRecipientListResponse|\Alexasomba\\Paystack\Model\Error|\Alexasomba\\Paystack\Model\Error
     */
    public function transferrecipientList($per_page = null, $page = null, $from = null, $to = null, string $contentType = self::contentTypes['transferrecipientList'][0])
    {
        list($response) = $this->transferrecipientListWithHttpInfo($per_page, $page, $from, $to, $contentType);
        return $response;
    }

    /**
     * Operation transferrecipientListWithHttpInfo
     *
     * List Transfer Recipients
     *
     * @param  int|null $per_page Specify how many records you want to retrieve per page. If not specified, we use a default value of 50. (optional)
     * @param  int|null $page Specify exactly what page you want to retrieve. If not specified, we use a default value of 1. (optional)
     * @param  \DateTime|null $from A timestamp from which to start listing transfer recipients e.g. 2016-09-24T00:00:05.000Z, 2016-09-21 (optional)
     * @param  \DateTime|null $to A timestamp at which to stop listing transfer recipients e.g. 2016-09-24T00:00:05.000Z, 2016-09-21 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientList'] to see the possible values for this operation
     *
     * @throws \Alexasomba\\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Alexasomba\\Paystack\Model\TransferRecipientListResponse|\Alexasomba\\Paystack\Model\Error|\Alexasomba\\Paystack\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function transferrecipientListWithHttpInfo($per_page = null, $page = null, $from = null, $to = null, string $contentType = self::contentTypes['transferrecipientList'][0])
    {
        $request = $this->transferrecipientListRequest($per_page, $page, $from, $to, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\TransferRecipientListResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\Error',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Alexasomba\\Paystack\Model\TransferRecipientListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\TransferRecipientListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation transferrecipientListAsync
     *
     * List Transfer Recipients
     *
     * @param  int|null $per_page Specify how many records you want to retrieve per page. If not specified, we use a default value of 50. (optional)
     * @param  int|null $page Specify exactly what page you want to retrieve. If not specified, we use a default value of 1. (optional)
     * @param  \DateTime|null $from A timestamp from which to start listing transfer recipients e.g. 2016-09-24T00:00:05.000Z, 2016-09-21 (optional)
     * @param  \DateTime|null $to A timestamp at which to stop listing transfer recipients e.g. 2016-09-24T00:00:05.000Z, 2016-09-21 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferrecipientListAsync($per_page = null, $page = null, $from = null, $to = null, string $contentType = self::contentTypes['transferrecipientList'][0])
    {
        return $this->transferrecipientListAsyncWithHttpInfo($per_page, $page, $from, $to, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation transferrecipientListAsyncWithHttpInfo
     *
     * List Transfer Recipients
     *
     * @param  int|null $per_page Specify how many records you want to retrieve per page. If not specified, we use a default value of 50. (optional)
     * @param  int|null $page Specify exactly what page you want to retrieve. If not specified, we use a default value of 1. (optional)
     * @param  \DateTime|null $from A timestamp from which to start listing transfer recipients e.g. 2016-09-24T00:00:05.000Z, 2016-09-21 (optional)
     * @param  \DateTime|null $to A timestamp at which to stop listing transfer recipients e.g. 2016-09-24T00:00:05.000Z, 2016-09-21 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferrecipientListAsyncWithHttpInfo($per_page = null, $page = null, $from = null, $to = null, string $contentType = self::contentTypes['transferrecipientList'][0])
    {
        $returnType = '\Alexasomba\\Paystack\Model\TransferRecipientListResponse';
        $request = $this->transferrecipientListRequest($per_page, $page, $from, $to, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'transferrecipientList'
     *
     * @param  int|null $per_page Specify how many records you want to retrieve per page. If not specified, we use a default value of 50. (optional)
     * @param  int|null $page Specify exactly what page you want to retrieve. If not specified, we use a default value of 1. (optional)
     * @param  \DateTime|null $from A timestamp from which to start listing transfer recipients e.g. 2016-09-24T00:00:05.000Z, 2016-09-21 (optional)
     * @param  \DateTime|null $to A timestamp at which to stop listing transfer recipients e.g. 2016-09-24T00:00:05.000Z, 2016-09-21 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function transferrecipientListRequest($per_page = null, $page = null, $from = null, $to = null, string $contentType = self::contentTypes['transferrecipientList'][0])
    {






        $resourcePath = '/transferrecipient';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'perPage', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $from,
            'from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $to,
            'to', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation transferrecipientUpdate
     *
     * Update Transfer Recipient
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientUpdate|null $transfer_recipient_update transfer_recipient_update (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientUpdate'] to see the possible values for this operation
     *
     * @throws \Alexasomba\\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Alexasomba\\Paystack\Model\TransferRecipientUpdateResponse|\Alexasomba\\Paystack\Model\Error|\Alexasomba\\Paystack\Model\Error
     */
    public function transferrecipientUpdate($id_or_code, $transfer_recipient_update = null, string $contentType = self::contentTypes['transferrecipientUpdate'][0])
    {
        list($response) = $this->transferrecipientUpdateWithHttpInfo($id_or_code, $transfer_recipient_update, $contentType);
        return $response;
    }

    /**
     * Operation transferrecipientUpdateWithHttpInfo
     *
     * Update Transfer Recipient
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientUpdate|null $transfer_recipient_update (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientUpdate'] to see the possible values for this operation
     *
     * @throws \Alexasomba\\Paystack\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Alexasomba\\Paystack\Model\TransferRecipientUpdateResponse|\Alexasomba\\Paystack\Model\Error|\Alexasomba\\Paystack\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function transferrecipientUpdateWithHttpInfo($id_or_code, $transfer_recipient_update = null, string $contentType = self::contentTypes['transferrecipientUpdate'][0])
    {
        $request = $this->transferrecipientUpdateRequest($id_or_code, $transfer_recipient_update, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\TransferRecipientUpdateResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\Error',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Alexasomba\\Paystack\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Alexasomba\\Paystack\Model\TransferRecipientUpdateResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\TransferRecipientUpdateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Alexasomba\\Paystack\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation transferrecipientUpdateAsync
     *
     * Update Transfer Recipient
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientUpdate|null $transfer_recipient_update (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferrecipientUpdateAsync($id_or_code, $transfer_recipient_update = null, string $contentType = self::contentTypes['transferrecipientUpdate'][0])
    {
        return $this->transferrecipientUpdateAsyncWithHttpInfo($id_or_code, $transfer_recipient_update, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation transferrecipientUpdateAsyncWithHttpInfo
     *
     * Update Transfer Recipient
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientUpdate|null $transfer_recipient_update (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferrecipientUpdateAsyncWithHttpInfo($id_or_code, $transfer_recipient_update = null, string $contentType = self::contentTypes['transferrecipientUpdate'][0])
    {
        $returnType = '\Alexasomba\\Paystack\Model\TransferRecipientUpdateResponse';
        $request = $this->transferrecipientUpdateRequest($id_or_code, $transfer_recipient_update, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'transferrecipientUpdate'
     *
     * @param  string $id_or_code An ID or code for the recipient whose details you want to receive. (required)
     * @param  \Alexasomba\\Paystack\Model\TransferRecipientUpdate|null $transfer_recipient_update (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferrecipientUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function transferrecipientUpdateRequest($id_or_code, $transfer_recipient_update = null, string $contentType = self::contentTypes['transferrecipientUpdate'][0])
    {

        // verify the required parameter 'id_or_code' is set
        if ($id_or_code === null || (is_array($id_or_code) && count($id_or_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_or_code when calling transferrecipientUpdate'
            );
        }



        $resourcePath = '/transferrecipient/{id_or_code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id_or_code !== null) {
            $resourcePath = str_replace(
                '{' . 'id_or_code' . '}',
                ObjectSerializer::toPathValue($id_or_code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($transfer_recipient_update)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($transfer_recipient_update));
            } else {
                $httpBody = $transfer_recipient_update;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
