<?php
/**
 * OrderFetchProductResponseArray
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Alexasomba\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paystack
 *
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: techsupport@paystack.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Alexasomba\Paystack\Model;

use \ArrayAccess;
use \Alexasomba\Paystack\ObjectSerializer;

/**
 * OrderFetchProductResponseArray Class Doc Comment
 *
 * @category Class
 * @package  Alexasomba\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OrderFetchProductResponseArray implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OrderFetchProductResponseArray';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'orderId' => 'int',
        'transaction' => 'int',
        'orderCode' => 'string',
        'customer' => 'int',
        'firstName' => 'string',
        'lastName' => 'string',
        'customerName' => 'string',
        'phone' => 'string',
        'email' => 'string',
        'productCode' => 'string',
        'productId' => 'int',
        'productName' => 'string',
        'price' => 'int',
        'quantitySold' => 'int',
        'currency' => 'string',
        'quantity' => 'int',
        'variantId' => 'mixed',
        'variantPrice' => 'mixed',
        'variantCode' => 'mixed',
        'amount' => 'int',
        'shippingMethod' => 'mixed',
        'status' => 'string',
        'shippingAddress' => 'mixed',
        'refunded' => 'bool',
        'shipping' => 'mixed',
        'paidAt' => 'string',
        'createdAt' => 'string',
        'isShipped' => 'bool',
        'isViewed' => 'int',
        'deliveryNote' => 'mixed',
        'shippingFee' => 'mixed',
        'amountPaid' => 'int',
        'storefrontSlug' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'orderId' => null,
        'transaction' => null,
        'orderCode' => null,
        'customer' => null,
        'firstName' => null,
        'lastName' => null,
        'customerName' => null,
        'phone' => null,
        'email' => null,
        'productCode' => null,
        'productId' => null,
        'productName' => null,
        'price' => null,
        'quantitySold' => null,
        'currency' => null,
        'quantity' => null,
        'variantId' => null,
        'variantPrice' => null,
        'variantCode' => null,
        'amount' => null,
        'shippingMethod' => null,
        'status' => null,
        'shippingAddress' => null,
        'refunded' => null,
        'shipping' => null,
        'paidAt' => null,
        'createdAt' => null,
        'isShipped' => null,
        'isViewed' => null,
        'deliveryNote' => null,
        'shippingFee' => null,
        'amountPaid' => null,
        'storefrontSlug' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'orderId' => false,
        'transaction' => false,
        'orderCode' => false,
        'customer' => false,
        'firstName' => false,
        'lastName' => false,
        'customerName' => false,
        'phone' => false,
        'email' => false,
        'productCode' => false,
        'productId' => false,
        'productName' => false,
        'price' => false,
        'quantitySold' => false,
        'currency' => false,
        'quantity' => false,
        'variantId' => true,
        'variantPrice' => true,
        'variantCode' => true,
        'amount' => false,
        'shippingMethod' => true,
        'status' => false,
        'shippingAddress' => true,
        'refunded' => false,
        'shipping' => true,
        'paidAt' => false,
        'createdAt' => false,
        'isShipped' => false,
        'isViewed' => false,
        'deliveryNote' => true,
        'shippingFee' => true,
        'amountPaid' => false,
        'storefrontSlug' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'orderId' => 'order_id',
        'transaction' => 'transaction',
        'orderCode' => 'order_code',
        'customer' => 'customer',
        'firstName' => 'first_name',
        'lastName' => 'last_name',
        'customerName' => 'customer_name',
        'phone' => 'phone',
        'email' => 'email',
        'productCode' => 'product_code',
        'productId' => 'product_id',
        'productName' => 'product_name',
        'price' => 'price',
        'quantitySold' => 'quantity_sold',
        'currency' => 'currency',
        'quantity' => 'quantity',
        'variantId' => 'variant_id',
        'variantPrice' => 'variant_price',
        'variantCode' => 'variant_code',
        'amount' => 'amount',
        'shippingMethod' => 'shipping_method',
        'status' => 'status',
        'shippingAddress' => 'shipping_address',
        'refunded' => 'refunded',
        'shipping' => 'shipping',
        'paidAt' => 'paid_at',
        'createdAt' => 'created_at',
        'isShipped' => 'is_shipped',
        'isViewed' => 'is_viewed',
        'deliveryNote' => 'delivery_note',
        'shippingFee' => 'shipping_fee',
        'amountPaid' => 'amount_paid',
        'storefrontSlug' => 'storefront_slug'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'orderId' => 'setOrderId',
        'transaction' => 'setTransaction',
        'orderCode' => 'setOrderCode',
        'customer' => 'setCustomer',
        'firstName' => 'setFirstName',
        'lastName' => 'setLastName',
        'customerName' => 'setCustomerName',
        'phone' => 'setPhone',
        'email' => 'setEmail',
        'productCode' => 'setProductCode',
        'productId' => 'setProductId',
        'productName' => 'setProductName',
        'price' => 'setPrice',
        'quantitySold' => 'setQuantitySold',
        'currency' => 'setCurrency',
        'quantity' => 'setQuantity',
        'variantId' => 'setVariantId',
        'variantPrice' => 'setVariantPrice',
        'variantCode' => 'setVariantCode',
        'amount' => 'setAmount',
        'shippingMethod' => 'setShippingMethod',
        'status' => 'setStatus',
        'shippingAddress' => 'setShippingAddress',
        'refunded' => 'setRefunded',
        'shipping' => 'setShipping',
        'paidAt' => 'setPaidAt',
        'createdAt' => 'setCreatedAt',
        'isShipped' => 'setIsShipped',
        'isViewed' => 'setIsViewed',
        'deliveryNote' => 'setDeliveryNote',
        'shippingFee' => 'setShippingFee',
        'amountPaid' => 'setAmountPaid',
        'storefrontSlug' => 'setStorefrontSlug'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'orderId' => 'getOrderId',
        'transaction' => 'getTransaction',
        'orderCode' => 'getOrderCode',
        'customer' => 'getCustomer',
        'firstName' => 'getFirstName',
        'lastName' => 'getLastName',
        'customerName' => 'getCustomerName',
        'phone' => 'getPhone',
        'email' => 'getEmail',
        'productCode' => 'getProductCode',
        'productId' => 'getProductId',
        'productName' => 'getProductName',
        'price' => 'getPrice',
        'quantitySold' => 'getQuantitySold',
        'currency' => 'getCurrency',
        'quantity' => 'getQuantity',
        'variantId' => 'getVariantId',
        'variantPrice' => 'getVariantPrice',
        'variantCode' => 'getVariantCode',
        'amount' => 'getAmount',
        'shippingMethod' => 'getShippingMethod',
        'status' => 'getStatus',
        'shippingAddress' => 'getShippingAddress',
        'refunded' => 'getRefunded',
        'shipping' => 'getShipping',
        'paidAt' => 'getPaidAt',
        'createdAt' => 'getCreatedAt',
        'isShipped' => 'getIsShipped',
        'isViewed' => 'getIsViewed',
        'deliveryNote' => 'getDeliveryNote',
        'shippingFee' => 'getShippingFee',
        'amountPaid' => 'getAmountPaid',
        'storefrontSlug' => 'getStorefrontSlug'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('orderId', $data ?? [], null);
        $this->setIfExists('transaction', $data ?? [], null);
        $this->setIfExists('orderCode', $data ?? [], null);
        $this->setIfExists('customer', $data ?? [], null);
        $this->setIfExists('firstName', $data ?? [], null);
        $this->setIfExists('lastName', $data ?? [], null);
        $this->setIfExists('customerName', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('productCode', $data ?? [], null);
        $this->setIfExists('productId', $data ?? [], null);
        $this->setIfExists('productName', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('quantitySold', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('variantId', $data ?? [], null);
        $this->setIfExists('variantPrice', $data ?? [], null);
        $this->setIfExists('variantCode', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('shippingMethod', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('shippingAddress', $data ?? [], null);
        $this->setIfExists('refunded', $data ?? [], null);
        $this->setIfExists('shipping', $data ?? [], null);
        $this->setIfExists('paidAt', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('isShipped', $data ?? [], null);
        $this->setIfExists('isViewed', $data ?? [], null);
        $this->setIfExists('deliveryNote', $data ?? [], null);
        $this->setIfExists('shippingFee', $data ?? [], null);
        $this->setIfExists('amountPaid', $data ?? [], null);
        $this->setIfExists('storefrontSlug', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['orderId'] === null) {
            $invalidProperties[] = "'orderId' can't be null";
        }
        if ($this->container['transaction'] === null) {
            $invalidProperties[] = "'transaction' can't be null";
        }
        if ($this->container['orderCode'] === null) {
            $invalidProperties[] = "'orderCode' can't be null";
        }
        if ($this->container['customer'] === null) {
            $invalidProperties[] = "'customer' can't be null";
        }
        if ($this->container['firstName'] === null) {
            $invalidProperties[] = "'firstName' can't be null";
        }
        if ($this->container['lastName'] === null) {
            $invalidProperties[] = "'lastName' can't be null";
        }
        if ($this->container['customerName'] === null) {
            $invalidProperties[] = "'customerName' can't be null";
        }
        if ($this->container['phone'] === null) {
            $invalidProperties[] = "'phone' can't be null";
        }
        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        if ($this->container['productCode'] === null) {
            $invalidProperties[] = "'productCode' can't be null";
        }
        if ($this->container['productId'] === null) {
            $invalidProperties[] = "'productId' can't be null";
        }
        if ($this->container['productName'] === null) {
            $invalidProperties[] = "'productName' can't be null";
        }
        if ($this->container['price'] === null) {
            $invalidProperties[] = "'price' can't be null";
        }
        if ($this->container['quantitySold'] === null) {
            $invalidProperties[] = "'quantitySold' can't be null";
        }
        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if ($this->container['variantId'] === null && !$this->isNullableSetToNull('variantId')) {
            $invalidProperties[] = "'variantId' can't be null";
        }
        if ($this->container['variantPrice'] === null && !$this->isNullableSetToNull('variantPrice')) {
            $invalidProperties[] = "'variantPrice' can't be null";
        }
        if ($this->container['variantCode'] === null && !$this->isNullableSetToNull('variantCode')) {
            $invalidProperties[] = "'variantCode' can't be null";
        }
        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if ($this->container['shippingMethod'] === null && !$this->isNullableSetToNull('shippingMethod')) {
            $invalidProperties[] = "'shippingMethod' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['shippingAddress'] === null && !$this->isNullableSetToNull('shippingAddress')) {
            $invalidProperties[] = "'shippingAddress' can't be null";
        }
        if ($this->container['refunded'] === null) {
            $invalidProperties[] = "'refunded' can't be null";
        }
        if ($this->container['shipping'] === null && !$this->isNullableSetToNull('shipping')) {
            $invalidProperties[] = "'shipping' can't be null";
        }
        if ($this->container['paidAt'] === null) {
            $invalidProperties[] = "'paidAt' can't be null";
        }
        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['isShipped'] === null) {
            $invalidProperties[] = "'isShipped' can't be null";
        }
        if ($this->container['isViewed'] === null) {
            $invalidProperties[] = "'isViewed' can't be null";
        }
        if ($this->container['deliveryNote'] === null && !$this->isNullableSetToNull('deliveryNote')) {
            $invalidProperties[] = "'deliveryNote' can't be null";
        }
        if ($this->container['shippingFee'] === null && !$this->isNullableSetToNull('shippingFee')) {
            $invalidProperties[] = "'shippingFee' can't be null";
        }
        if ($this->container['amountPaid'] === null) {
            $invalidProperties[] = "'amountPaid' can't be null";
        }
        if ($this->container['storefrontSlug'] === null) {
            $invalidProperties[] = "'storefrontSlug' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets orderId
     *
     * @return int
     */
    public function getOrderId()
    {
        return $this->container['orderId'];
    }

    /**
     * Sets orderId
     *
     * @param int $orderId orderId
     *
     * @return self
     */
    public function setOrderId($orderId)
    {
        if (is_null($orderId)) {
            throw new \InvalidArgumentException('non-nullable orderId cannot be null');
        }
        $this->container['orderId'] = $orderId;

        return $this;
    }

    /**
     * Gets transaction
     *
     * @return int
     */
    public function getTransaction()
    {
        return $this->container['transaction'];
    }

    /**
     * Sets transaction
     *
     * @param int $transaction transaction
     *
     * @return self
     */
    public function setTransaction($transaction)
    {
        if (is_null($transaction)) {
            throw new \InvalidArgumentException('non-nullable transaction cannot be null');
        }
        $this->container['transaction'] = $transaction;

        return $this;
    }

    /**
     * Gets orderCode
     *
     * @return string
     */
    public function getOrderCode()
    {
        return $this->container['orderCode'];
    }

    /**
     * Sets orderCode
     *
     * @param string $orderCode orderCode
     *
     * @return self
     */
    public function setOrderCode($orderCode)
    {
        if (is_null($orderCode)) {
            throw new \InvalidArgumentException('non-nullable orderCode cannot be null');
        }
        $this->container['orderCode'] = $orderCode;

        return $this;
    }

    /**
     * Gets customer
     *
     * @return int
     */
    public function getCustomer()
    {
        return $this->container['customer'];
    }

    /**
     * Sets customer
     *
     * @param int $customer customer
     *
     * @return self
     */
    public function setCustomer($customer)
    {
        if (is_null($customer)) {
            throw new \InvalidArgumentException('non-nullable customer cannot be null');
        }
        $this->container['customer'] = $customer;

        return $this;
    }

    /**
     * Gets firstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->container['firstName'];
    }

    /**
     * Sets firstName
     *
     * @param string $firstName firstName
     *
     * @return self
     */
    public function setFirstName($firstName)
    {
        if (is_null($firstName)) {
            throw new \InvalidArgumentException('non-nullable firstName cannot be null');
        }
        $this->container['firstName'] = $firstName;

        return $this;
    }

    /**
     * Gets lastName
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->container['lastName'];
    }

    /**
     * Sets lastName
     *
     * @param string $lastName lastName
     *
     * @return self
     */
    public function setLastName($lastName)
    {
        if (is_null($lastName)) {
            throw new \InvalidArgumentException('non-nullable lastName cannot be null');
        }
        $this->container['lastName'] = $lastName;

        return $this;
    }

    /**
     * Gets customerName
     *
     * @return string
     */
    public function getCustomerName()
    {
        return $this->container['customerName'];
    }

    /**
     * Sets customerName
     *
     * @param string $customerName customerName
     *
     * @return self
     */
    public function setCustomerName($customerName)
    {
        if (is_null($customerName)) {
            throw new \InvalidArgumentException('non-nullable customerName cannot be null');
        }
        $this->container['customerName'] = $customerName;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string $phone phone
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets productCode
     *
     * @return string
     */
    public function getProductCode()
    {
        return $this->container['productCode'];
    }

    /**
     * Sets productCode
     *
     * @param string $productCode productCode
     *
     * @return self
     */
    public function setProductCode($productCode)
    {
        if (is_null($productCode)) {
            throw new \InvalidArgumentException('non-nullable productCode cannot be null');
        }
        $this->container['productCode'] = $productCode;

        return $this;
    }

    /**
     * Gets productId
     *
     * @return int
     */
    public function getProductId()
    {
        return $this->container['productId'];
    }

    /**
     * Sets productId
     *
     * @param int $productId productId
     *
     * @return self
     */
    public function setProductId($productId)
    {
        if (is_null($productId)) {
            throw new \InvalidArgumentException('non-nullable productId cannot be null');
        }
        $this->container['productId'] = $productId;

        return $this;
    }

    /**
     * Gets productName
     *
     * @return string
     */
    public function getProductName()
    {
        return $this->container['productName'];
    }

    /**
     * Sets productName
     *
     * @param string $productName productName
     *
     * @return self
     */
    public function setProductName($productName)
    {
        if (is_null($productName)) {
            throw new \InvalidArgumentException('non-nullable productName cannot be null');
        }
        $this->container['productName'] = $productName;

        return $this;
    }

    /**
     * Gets price
     *
     * @return int
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param int $price price
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets quantitySold
     *
     * @return int
     */
    public function getQuantitySold()
    {
        return $this->container['quantitySold'];
    }

    /**
     * Sets quantitySold
     *
     * @param int $quantitySold quantitySold
     *
     * @return self
     */
    public function setQuantitySold($quantitySold)
    {
        if (is_null($quantitySold)) {
            throw new \InvalidArgumentException('non-nullable quantitySold cannot be null');
        }
        $this->container['quantitySold'] = $quantitySold;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return int
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param int $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets variantId
     *
     * @return mixed|null
     */
    public function getVariantId()
    {
        return $this->container['variantId'];
    }

    /**
     * Sets variantId
     *
     * @param mixed|null $variantId variantId
     *
     * @return self
     */
    public function setVariantId($variantId)
    {
        if (is_null($variantId)) {
            array_push($this->openAPINullablesSetToNull, 'variantId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('variantId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['variantId'] = $variantId;

        return $this;
    }

    /**
     * Gets variantPrice
     *
     * @return mixed|null
     */
    public function getVariantPrice()
    {
        return $this->container['variantPrice'];
    }

    /**
     * Sets variantPrice
     *
     * @param mixed|null $variantPrice variantPrice
     *
     * @return self
     */
    public function setVariantPrice($variantPrice)
    {
        if (is_null($variantPrice)) {
            array_push($this->openAPINullablesSetToNull, 'variantPrice');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('variantPrice', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['variantPrice'] = $variantPrice;

        return $this;
    }

    /**
     * Gets variantCode
     *
     * @return mixed|null
     */
    public function getVariantCode()
    {
        return $this->container['variantCode'];
    }

    /**
     * Sets variantCode
     *
     * @param mixed|null $variantCode variantCode
     *
     * @return self
     */
    public function setVariantCode($variantCode)
    {
        if (is_null($variantCode)) {
            array_push($this->openAPINullablesSetToNull, 'variantCode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('variantCode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['variantCode'] = $variantCode;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return int
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets shippingMethod
     *
     * @return mixed|null
     */
    public function getShippingMethod()
    {
        return $this->container['shippingMethod'];
    }

    /**
     * Sets shippingMethod
     *
     * @param mixed|null $shippingMethod shippingMethod
     *
     * @return self
     */
    public function setShippingMethod($shippingMethod)
    {
        if (is_null($shippingMethod)) {
            array_push($this->openAPINullablesSetToNull, 'shippingMethod');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shippingMethod', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shippingMethod'] = $shippingMethod;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets shippingAddress
     *
     * @return mixed|null
     */
    public function getShippingAddress()
    {
        return $this->container['shippingAddress'];
    }

    /**
     * Sets shippingAddress
     *
     * @param mixed|null $shippingAddress shippingAddress
     *
     * @return self
     */
    public function setShippingAddress($shippingAddress)
    {
        if (is_null($shippingAddress)) {
            array_push($this->openAPINullablesSetToNull, 'shippingAddress');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shippingAddress', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shippingAddress'] = $shippingAddress;

        return $this;
    }

    /**
     * Gets refunded
     *
     * @return bool
     */
    public function getRefunded()
    {
        return $this->container['refunded'];
    }

    /**
     * Sets refunded
     *
     * @param bool $refunded refunded
     *
     * @return self
     */
    public function setRefunded($refunded)
    {
        if (is_null($refunded)) {
            throw new \InvalidArgumentException('non-nullable refunded cannot be null');
        }
        $this->container['refunded'] = $refunded;

        return $this;
    }

    /**
     * Gets shipping
     *
     * @return mixed|null
     */
    public function getShipping()
    {
        return $this->container['shipping'];
    }

    /**
     * Sets shipping
     *
     * @param mixed|null $shipping shipping
     *
     * @return self
     */
    public function setShipping($shipping)
    {
        if (is_null($shipping)) {
            array_push($this->openAPINullablesSetToNull, 'shipping');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shipping', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shipping'] = $shipping;

        return $this;
    }

    /**
     * Gets paidAt
     *
     * @return string
     */
    public function getPaidAt()
    {
        return $this->container['paidAt'];
    }

    /**
     * Sets paidAt
     *
     * @param string $paidAt paidAt
     *
     * @return self
     */
    public function setPaidAt($paidAt)
    {
        if (is_null($paidAt)) {
            throw new \InvalidArgumentException('non-nullable paidAt cannot be null');
        }
        $this->container['paidAt'] = $paidAt;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param string $createdAt createdAt
     *
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        if (is_null($createdAt)) {
            throw new \InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets isShipped
     *
     * @return bool
     */
    public function getIsShipped()
    {
        return $this->container['isShipped'];
    }

    /**
     * Sets isShipped
     *
     * @param bool $isShipped isShipped
     *
     * @return self
     */
    public function setIsShipped($isShipped)
    {
        if (is_null($isShipped)) {
            throw new \InvalidArgumentException('non-nullable isShipped cannot be null');
        }
        $this->container['isShipped'] = $isShipped;

        return $this;
    }

    /**
     * Gets isViewed
     *
     * @return int
     */
    public function getIsViewed()
    {
        return $this->container['isViewed'];
    }

    /**
     * Sets isViewed
     *
     * @param int $isViewed isViewed
     *
     * @return self
     */
    public function setIsViewed($isViewed)
    {
        if (is_null($isViewed)) {
            throw new \InvalidArgumentException('non-nullable isViewed cannot be null');
        }
        $this->container['isViewed'] = $isViewed;

        return $this;
    }

    /**
     * Gets deliveryNote
     *
     * @return mixed|null
     */
    public function getDeliveryNote()
    {
        return $this->container['deliveryNote'];
    }

    /**
     * Sets deliveryNote
     *
     * @param mixed|null $deliveryNote deliveryNote
     *
     * @return self
     */
    public function setDeliveryNote($deliveryNote)
    {
        if (is_null($deliveryNote)) {
            array_push($this->openAPINullablesSetToNull, 'deliveryNote');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deliveryNote', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deliveryNote'] = $deliveryNote;

        return $this;
    }

    /**
     * Gets shippingFee
     *
     * @return mixed|null
     */
    public function getShippingFee()
    {
        return $this->container['shippingFee'];
    }

    /**
     * Sets shippingFee
     *
     * @param mixed|null $shippingFee shippingFee
     *
     * @return self
     */
    public function setShippingFee($shippingFee)
    {
        if (is_null($shippingFee)) {
            array_push($this->openAPINullablesSetToNull, 'shippingFee');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shippingFee', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shippingFee'] = $shippingFee;

        return $this;
    }

    /**
     * Gets amountPaid
     *
     * @return int
     */
    public function getAmountPaid()
    {
        return $this->container['amountPaid'];
    }

    /**
     * Sets amountPaid
     *
     * @param int $amountPaid amountPaid
     *
     * @return self
     */
    public function setAmountPaid($amountPaid)
    {
        if (is_null($amountPaid)) {
            throw new \InvalidArgumentException('non-nullable amountPaid cannot be null');
        }
        $this->container['amountPaid'] = $amountPaid;

        return $this;
    }

    /**
     * Gets storefrontSlug
     *
     * @return string
     */
    public function getStorefrontSlug()
    {
        return $this->container['storefrontSlug'];
    }

    /**
     * Sets storefrontSlug
     *
     * @param string $storefrontSlug storefrontSlug
     *
     * @return self
     */
    public function setStorefrontSlug($storefrontSlug)
    {
        if (is_null($storefrontSlug)) {
            throw new \InvalidArgumentException('non-nullable storefrontSlug cannot be null');
        }
        $this->container['storefrontSlug'] = $storefrontSlug;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


