<?php
/**
 * PaymentRequestViewResponseData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Alexasomba\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paystack
 *
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: techsupport@paystack.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Alexasomba\Paystack\Model;

use \ArrayAccess;
use \Alexasomba\Paystack\ObjectSerializer;

/**
 * PaymentRequestViewResponseData Class Doc Comment
 *
 * @category Class
 * @package  Alexasomba\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PaymentRequestViewResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PaymentRequestViewResponse_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'domain' => 'string',
        'requestCode' => 'string',
        'description' => 'string',
        'lineItems' => '\Alexasomba\Paystack\Model\PaymentRequestLineItemsArray[]',
        'tax' => '\Alexasomba\Paystack\Model\PaymentRequestTaxArray[]',
        'amount' => 'int',
        'discount' => 'int',
        'currency' => 'string',
        'dueDate' => 'string',
        'status' => 'string',
        'paid' => 'bool',
        'paidAt' => 'string',
        'metadata' => 'object',
        'hasInvoice' => 'bool',
        'invoiceNumber' => 'int',
        'offlineReference' => 'string',
        'pdfUrl' => 'string',
        'notifications' => '\Alexasomba\Paystack\Model\PaymentRequestNotificationsArray[]',
        'archived' => 'bool',
        'source' => 'string',
        'paymentMethod' => 'string',
        'note' => 'string',
        'amountPaid' => 'int',
        'splitCode' => 'string',
        'id' => 'int',
        'integration' => 'int',
        'customer' => '\Alexasomba\Paystack\Model\PaymentRequestViewResponseDataCustomer',
        'createdAt' => 'string',
        'updatedAt' => 'string',
        'pendingAmount' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'domain' => null,
        'requestCode' => null,
        'description' => null,
        'lineItems' => null,
        'tax' => null,
        'amount' => null,
        'discount' => null,
        'currency' => null,
        'dueDate' => null,
        'status' => null,
        'paid' => null,
        'paidAt' => null,
        'metadata' => null,
        'hasInvoice' => null,
        'invoiceNumber' => null,
        'offlineReference' => null,
        'pdfUrl' => null,
        'notifications' => null,
        'archived' => null,
        'source' => null,
        'paymentMethod' => null,
        'note' => null,
        'amountPaid' => null,
        'splitCode' => null,
        'id' => null,
        'integration' => null,
        'customer' => null,
        'createdAt' => null,
        'updatedAt' => null,
        'pendingAmount' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'domain' => false,
        'requestCode' => false,
        'description' => true,
        'lineItems' => false,
        'tax' => false,
        'amount' => false,
        'discount' => true,
        'currency' => false,
        'dueDate' => true,
        'status' => false,
        'paid' => false,
        'paidAt' => true,
        'metadata' => true,
        'hasInvoice' => false,
        'invoiceNumber' => true,
        'offlineReference' => false,
        'pdfUrl' => true,
        'notifications' => false,
        'archived' => false,
        'source' => false,
        'paymentMethod' => true,
        'note' => true,
        'amountPaid' => true,
        'splitCode' => true,
        'id' => false,
        'integration' => false,
        'customer' => false,
        'createdAt' => false,
        'updatedAt' => false,
        'pendingAmount' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'domain' => 'domain',
        'requestCode' => 'request_code',
        'description' => 'description',
        'lineItems' => 'line_items',
        'tax' => 'tax',
        'amount' => 'amount',
        'discount' => 'discount',
        'currency' => 'currency',
        'dueDate' => 'due_date',
        'status' => 'status',
        'paid' => 'paid',
        'paidAt' => 'paid_at',
        'metadata' => 'metadata',
        'hasInvoice' => 'has_invoice',
        'invoiceNumber' => 'invoice_number',
        'offlineReference' => 'offline_reference',
        'pdfUrl' => 'pdf_url',
        'notifications' => 'notifications',
        'archived' => 'archived',
        'source' => 'source',
        'paymentMethod' => 'payment_method',
        'note' => 'note',
        'amountPaid' => 'amount_paid',
        'splitCode' => 'split_code',
        'id' => 'id',
        'integration' => 'integration',
        'customer' => 'customer',
        'createdAt' => 'createdAt',
        'updatedAt' => 'updatedAt',
        'pendingAmount' => 'pending_amount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'domain' => 'setDomain',
        'requestCode' => 'setRequestCode',
        'description' => 'setDescription',
        'lineItems' => 'setLineItems',
        'tax' => 'setTax',
        'amount' => 'setAmount',
        'discount' => 'setDiscount',
        'currency' => 'setCurrency',
        'dueDate' => 'setDueDate',
        'status' => 'setStatus',
        'paid' => 'setPaid',
        'paidAt' => 'setPaidAt',
        'metadata' => 'setMetadata',
        'hasInvoice' => 'setHasInvoice',
        'invoiceNumber' => 'setInvoiceNumber',
        'offlineReference' => 'setOfflineReference',
        'pdfUrl' => 'setPdfUrl',
        'notifications' => 'setNotifications',
        'archived' => 'setArchived',
        'source' => 'setSource',
        'paymentMethod' => 'setPaymentMethod',
        'note' => 'setNote',
        'amountPaid' => 'setAmountPaid',
        'splitCode' => 'setSplitCode',
        'id' => 'setId',
        'integration' => 'setIntegration',
        'customer' => 'setCustomer',
        'createdAt' => 'setCreatedAt',
        'updatedAt' => 'setUpdatedAt',
        'pendingAmount' => 'setPendingAmount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'domain' => 'getDomain',
        'requestCode' => 'getRequestCode',
        'description' => 'getDescription',
        'lineItems' => 'getLineItems',
        'tax' => 'getTax',
        'amount' => 'getAmount',
        'discount' => 'getDiscount',
        'currency' => 'getCurrency',
        'dueDate' => 'getDueDate',
        'status' => 'getStatus',
        'paid' => 'getPaid',
        'paidAt' => 'getPaidAt',
        'metadata' => 'getMetadata',
        'hasInvoice' => 'getHasInvoice',
        'invoiceNumber' => 'getInvoiceNumber',
        'offlineReference' => 'getOfflineReference',
        'pdfUrl' => 'getPdfUrl',
        'notifications' => 'getNotifications',
        'archived' => 'getArchived',
        'source' => 'getSource',
        'paymentMethod' => 'getPaymentMethod',
        'note' => 'getNote',
        'amountPaid' => 'getAmountPaid',
        'splitCode' => 'getSplitCode',
        'id' => 'getId',
        'integration' => 'getIntegration',
        'customer' => 'getCustomer',
        'createdAt' => 'getCreatedAt',
        'updatedAt' => 'getUpdatedAt',
        'pendingAmount' => 'getPendingAmount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('requestCode', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('lineItems', $data ?? [], null);
        $this->setIfExists('tax', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('discount', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('dueDate', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('paid', $data ?? [], null);
        $this->setIfExists('paidAt', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('hasInvoice', $data ?? [], null);
        $this->setIfExists('invoiceNumber', $data ?? [], null);
        $this->setIfExists('offlineReference', $data ?? [], null);
        $this->setIfExists('pdfUrl', $data ?? [], null);
        $this->setIfExists('notifications', $data ?? [], null);
        $this->setIfExists('archived', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('paymentMethod', $data ?? [], null);
        $this->setIfExists('note', $data ?? [], null);
        $this->setIfExists('amountPaid', $data ?? [], null);
        $this->setIfExists('splitCode', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('integration', $data ?? [], null);
        $this->setIfExists('customer', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
        $this->setIfExists('pendingAmount', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['domain'] === null) {
            $invalidProperties[] = "'domain' can't be null";
        }
        if ($this->container['requestCode'] === null) {
            $invalidProperties[] = "'requestCode' can't be null";
        }
        if ($this->container['description'] === null && !$this->isNullableSetToNull('description')) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['lineItems'] === null) {
            $invalidProperties[] = "'lineItems' can't be null";
        }
        if ($this->container['tax'] === null) {
            $invalidProperties[] = "'tax' can't be null";
        }
        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if ($this->container['discount'] === null && !$this->isNullableSetToNull('discount')) {
            $invalidProperties[] = "'discount' can't be null";
        }
        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        if ($this->container['dueDate'] === null && !$this->isNullableSetToNull('dueDate')) {
            $invalidProperties[] = "'dueDate' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['paid'] === null) {
            $invalidProperties[] = "'paid' can't be null";
        }
        if ($this->container['paidAt'] === null && !$this->isNullableSetToNull('paidAt')) {
            $invalidProperties[] = "'paidAt' can't be null";
        }
        if ($this->container['metadata'] === null && !$this->isNullableSetToNull('metadata')) {
            $invalidProperties[] = "'metadata' can't be null";
        }
        if ($this->container['hasInvoice'] === null) {
            $invalidProperties[] = "'hasInvoice' can't be null";
        }
        if ($this->container['invoiceNumber'] === null && !$this->isNullableSetToNull('invoiceNumber')) {
            $invalidProperties[] = "'invoiceNumber' can't be null";
        }
        if ($this->container['offlineReference'] === null) {
            $invalidProperties[] = "'offlineReference' can't be null";
        }
        if ($this->container['pdfUrl'] === null && !$this->isNullableSetToNull('pdfUrl')) {
            $invalidProperties[] = "'pdfUrl' can't be null";
        }
        if ($this->container['notifications'] === null) {
            $invalidProperties[] = "'notifications' can't be null";
        }
        if ($this->container['archived'] === null) {
            $invalidProperties[] = "'archived' can't be null";
        }
        if ($this->container['source'] === null) {
            $invalidProperties[] = "'source' can't be null";
        }
        if ($this->container['paymentMethod'] === null && !$this->isNullableSetToNull('paymentMethod')) {
            $invalidProperties[] = "'paymentMethod' can't be null";
        }
        if ($this->container['note'] === null && !$this->isNullableSetToNull('note')) {
            $invalidProperties[] = "'note' can't be null";
        }
        if ($this->container['amountPaid'] === null && !$this->isNullableSetToNull('amountPaid')) {
            $invalidProperties[] = "'amountPaid' can't be null";
        }
        if ($this->container['splitCode'] === null && !$this->isNullableSetToNull('splitCode')) {
            $invalidProperties[] = "'splitCode' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['integration'] === null) {
            $invalidProperties[] = "'integration' can't be null";
        }
        if ($this->container['customer'] === null) {
            $invalidProperties[] = "'customer' can't be null";
        }
        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['updatedAt'] === null) {
            $invalidProperties[] = "'updatedAt' can't be null";
        }
        if ($this->container['pendingAmount'] === null) {
            $invalidProperties[] = "'pendingAmount' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets domain
     *
     * @return string
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string $domain domain
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            throw new \InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets requestCode
     *
     * @return string
     */
    public function getRequestCode()
    {
        return $this->container['requestCode'];
    }

    /**
     * Sets requestCode
     *
     * @param string $requestCode requestCode
     *
     * @return self
     */
    public function setRequestCode($requestCode)
    {
        if (is_null($requestCode)) {
            throw new \InvalidArgumentException('non-nullable requestCode cannot be null');
        }
        $this->container['requestCode'] = $requestCode;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets lineItems
     *
     * @return \Alexasomba\Paystack\Model\PaymentRequestLineItemsArray[]
     */
    public function getLineItems()
    {
        return $this->container['lineItems'];
    }

    /**
     * Sets lineItems
     *
     * @param \Alexasomba\Paystack\Model\PaymentRequestLineItemsArray[] $lineItems lineItems
     *
     * @return self
     */
    public function setLineItems($lineItems)
    {
        if (is_null($lineItems)) {
            throw new \InvalidArgumentException('non-nullable lineItems cannot be null');
        }
        $this->container['lineItems'] = $lineItems;

        return $this;
    }

    /**
     * Gets tax
     *
     * @return \Alexasomba\Paystack\Model\PaymentRequestTaxArray[]
     */
    public function getTax()
    {
        return $this->container['tax'];
    }

    /**
     * Sets tax
     *
     * @param \Alexasomba\Paystack\Model\PaymentRequestTaxArray[] $tax tax
     *
     * @return self
     */
    public function setTax($tax)
    {
        if (is_null($tax)) {
            throw new \InvalidArgumentException('non-nullable tax cannot be null');
        }
        $this->container['tax'] = $tax;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return int
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets discount
     *
     * @return int|null
     */
    public function getDiscount()
    {
        return $this->container['discount'];
    }

    /**
     * Sets discount
     *
     * @param int|null $discount discount
     *
     * @return self
     */
    public function setDiscount($discount)
    {
        if (is_null($discount)) {
            array_push($this->openAPINullablesSetToNull, 'discount');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('discount', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['discount'] = $discount;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets dueDate
     *
     * @return string|null
     */
    public function getDueDate()
    {
        return $this->container['dueDate'];
    }

    /**
     * Sets dueDate
     *
     * @param string|null $dueDate dueDate
     *
     * @return self
     */
    public function setDueDate($dueDate)
    {
        if (is_null($dueDate)) {
            array_push($this->openAPINullablesSetToNull, 'dueDate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dueDate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dueDate'] = $dueDate;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets paid
     *
     * @return bool
     */
    public function getPaid()
    {
        return $this->container['paid'];
    }

    /**
     * Sets paid
     *
     * @param bool $paid paid
     *
     * @return self
     */
    public function setPaid($paid)
    {
        if (is_null($paid)) {
            throw new \InvalidArgumentException('non-nullable paid cannot be null');
        }
        $this->container['paid'] = $paid;

        return $this;
    }

    /**
     * Gets paidAt
     *
     * @return string|null
     */
    public function getPaidAt()
    {
        return $this->container['paidAt'];
    }

    /**
     * Sets paidAt
     *
     * @param string|null $paidAt paidAt
     *
     * @return self
     */
    public function setPaidAt($paidAt)
    {
        if (is_null($paidAt)) {
            array_push($this->openAPINullablesSetToNull, 'paidAt');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('paidAt', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['paidAt'] = $paidAt;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return object|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param object|null $metadata metadata
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            array_push($this->openAPINullablesSetToNull, 'metadata');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('metadata', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets hasInvoice
     *
     * @return bool
     */
    public function getHasInvoice()
    {
        return $this->container['hasInvoice'];
    }

    /**
     * Sets hasInvoice
     *
     * @param bool $hasInvoice hasInvoice
     *
     * @return self
     */
    public function setHasInvoice($hasInvoice)
    {
        if (is_null($hasInvoice)) {
            throw new \InvalidArgumentException('non-nullable hasInvoice cannot be null');
        }
        $this->container['hasInvoice'] = $hasInvoice;

        return $this;
    }

    /**
     * Gets invoiceNumber
     *
     * @return int|null
     */
    public function getInvoiceNumber()
    {
        return $this->container['invoiceNumber'];
    }

    /**
     * Sets invoiceNumber
     *
     * @param int|null $invoiceNumber invoiceNumber
     *
     * @return self
     */
    public function setInvoiceNumber($invoiceNumber)
    {
        if (is_null($invoiceNumber)) {
            array_push($this->openAPINullablesSetToNull, 'invoiceNumber');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoiceNumber', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoiceNumber'] = $invoiceNumber;

        return $this;
    }

    /**
     * Gets offlineReference
     *
     * @return string
     */
    public function getOfflineReference()
    {
        return $this->container['offlineReference'];
    }

    /**
     * Sets offlineReference
     *
     * @param string $offlineReference offlineReference
     *
     * @return self
     */
    public function setOfflineReference($offlineReference)
    {
        if (is_null($offlineReference)) {
            throw new \InvalidArgumentException('non-nullable offlineReference cannot be null');
        }
        $this->container['offlineReference'] = $offlineReference;

        return $this;
    }

    /**
     * Gets pdfUrl
     *
     * @return string|null
     */
    public function getPdfUrl()
    {
        return $this->container['pdfUrl'];
    }

    /**
     * Sets pdfUrl
     *
     * @param string|null $pdfUrl pdfUrl
     *
     * @return self
     */
    public function setPdfUrl($pdfUrl)
    {
        if (is_null($pdfUrl)) {
            array_push($this->openAPINullablesSetToNull, 'pdfUrl');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pdfUrl', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pdfUrl'] = $pdfUrl;

        return $this;
    }

    /**
     * Gets notifications
     *
     * @return \Alexasomba\Paystack\Model\PaymentRequestNotificationsArray[]
     */
    public function getNotifications()
    {
        return $this->container['notifications'];
    }

    /**
     * Sets notifications
     *
     * @param \Alexasomba\Paystack\Model\PaymentRequestNotificationsArray[] $notifications notifications
     *
     * @return self
     */
    public function setNotifications($notifications)
    {
        if (is_null($notifications)) {
            throw new \InvalidArgumentException('non-nullable notifications cannot be null');
        }
        $this->container['notifications'] = $notifications;

        return $this;
    }

    /**
     * Gets archived
     *
     * @return bool
     */
    public function getArchived()
    {
        return $this->container['archived'];
    }

    /**
     * Sets archived
     *
     * @param bool $archived archived
     *
     * @return self
     */
    public function setArchived($archived)
    {
        if (is_null($archived)) {
            throw new \InvalidArgumentException('non-nullable archived cannot be null');
        }
        $this->container['archived'] = $archived;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets paymentMethod
     *
     * @return string|null
     */
    public function getPaymentMethod()
    {
        return $this->container['paymentMethod'];
    }

    /**
     * Sets paymentMethod
     *
     * @param string|null $paymentMethod paymentMethod
     *
     * @return self
     */
    public function setPaymentMethod($paymentMethod)
    {
        if (is_null($paymentMethod)) {
            array_push($this->openAPINullablesSetToNull, 'paymentMethod');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('paymentMethod', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['paymentMethod'] = $paymentMethod;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string|null
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string|null $note note
     *
     * @return self
     */
    public function setNote($note)
    {
        if (is_null($note)) {
            array_push($this->openAPINullablesSetToNull, 'note');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('note', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets amountPaid
     *
     * @return int|null
     */
    public function getAmountPaid()
    {
        return $this->container['amountPaid'];
    }

    /**
     * Sets amountPaid
     *
     * @param int|null $amountPaid amountPaid
     *
     * @return self
     */
    public function setAmountPaid($amountPaid)
    {
        if (is_null($amountPaid)) {
            array_push($this->openAPINullablesSetToNull, 'amountPaid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('amountPaid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['amountPaid'] = $amountPaid;

        return $this;
    }

    /**
     * Gets splitCode
     *
     * @return string|null
     */
    public function getSplitCode()
    {
        return $this->container['splitCode'];
    }

    /**
     * Sets splitCode
     *
     * @param string|null $splitCode splitCode
     *
     * @return self
     */
    public function setSplitCode($splitCode)
    {
        if (is_null($splitCode)) {
            array_push($this->openAPINullablesSetToNull, 'splitCode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('splitCode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['splitCode'] = $splitCode;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets integration
     *
     * @return int
     */
    public function getIntegration()
    {
        return $this->container['integration'];
    }

    /**
     * Sets integration
     *
     * @param int $integration integration
     *
     * @return self
     */
    public function setIntegration($integration)
    {
        if (is_null($integration)) {
            throw new \InvalidArgumentException('non-nullable integration cannot be null');
        }
        $this->container['integration'] = $integration;

        return $this;
    }

    /**
     * Gets customer
     *
     * @return \Alexasomba\Paystack\Model\PaymentRequestViewResponseDataCustomer
     */
    public function getCustomer()
    {
        return $this->container['customer'];
    }

    /**
     * Sets customer
     *
     * @param \Alexasomba\Paystack\Model\PaymentRequestViewResponseDataCustomer $customer customer
     *
     * @return self
     */
    public function setCustomer($customer)
    {
        if (is_null($customer)) {
            throw new \InvalidArgumentException('non-nullable customer cannot be null');
        }
        $this->container['customer'] = $customer;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param string $createdAt createdAt
     *
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        if (is_null($createdAt)) {
            throw new \InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param string $updatedAt updatedAt
     *
     * @return self
     */
    public function setUpdatedAt($updatedAt)
    {
        if (is_null($updatedAt)) {
            throw new \InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }

    /**
     * Gets pendingAmount
     *
     * @return int
     */
    public function getPendingAmount()
    {
        return $this->container['pendingAmount'];
    }

    /**
     * Sets pendingAmount
     *
     * @param int $pendingAmount pendingAmount
     *
     * @return self
     */
    public function setPendingAmount($pendingAmount)
    {
        if (is_null($pendingAmount)) {
            throw new \InvalidArgumentException('non-nullable pendingAmount cannot be null');
        }
        $this->container['pendingAmount'] = $pendingAmount;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


