<?php
/**
 * PreAuthorizationInitialize
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Alexasomba\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paystack
 *
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: techsupport@paystack.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Alexasomba\Paystack\Model;

use \ArrayAccess;
use \Alexasomba\Paystack\ObjectSerializer;

/**
 * PreAuthorizationInitialize Class Doc Comment
 *
 * @category Class
 * @package  Alexasomba\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PreAuthorizationInitialize implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PreAuthorizationInitialize';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'amount' => 'string',
        'email' => 'string',
        'currency' => 'string',
        'reference' => 'string',
        'callbackUrl' => 'string',
        'metadata' => '\Alexasomba\Paystack\Model\PreAuthorizationInitializeMetadata',
        'splitCode' => 'string',
        'subaccount' => 'string',
        'transactionCharge' => 'int',
        'bearer' => 'string',
        'expireAction' => 'string',
        'expireAfterDays' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'amount' => null,
        'email' => null,
        'currency' => null,
        'reference' => null,
        'callbackUrl' => null,
        'metadata' => null,
        'splitCode' => null,
        'subaccount' => null,
        'transactionCharge' => null,
        'bearer' => null,
        'expireAction' => null,
        'expireAfterDays' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'amount' => false,
        'email' => false,
        'currency' => false,
        'reference' => false,
        'callbackUrl' => false,
        'metadata' => false,
        'splitCode' => false,
        'subaccount' => false,
        'transactionCharge' => false,
        'bearer' => false,
        'expireAction' => false,
        'expireAfterDays' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'amount' => 'amount',
        'email' => 'email',
        'currency' => 'currency',
        'reference' => 'reference',
        'callbackUrl' => 'callback_url',
        'metadata' => 'metadata',
        'splitCode' => 'split_code',
        'subaccount' => 'subaccount',
        'transactionCharge' => 'transaction_charge',
        'bearer' => 'bearer',
        'expireAction' => 'expire_action',
        'expireAfterDays' => 'expire_after_days'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'amount' => 'setAmount',
        'email' => 'setEmail',
        'currency' => 'setCurrency',
        'reference' => 'setReference',
        'callbackUrl' => 'setCallbackUrl',
        'metadata' => 'setMetadata',
        'splitCode' => 'setSplitCode',
        'subaccount' => 'setSubaccount',
        'transactionCharge' => 'setTransactionCharge',
        'bearer' => 'setBearer',
        'expireAction' => 'setExpireAction',
        'expireAfterDays' => 'setExpireAfterDays'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'amount' => 'getAmount',
        'email' => 'getEmail',
        'currency' => 'getCurrency',
        'reference' => 'getReference',
        'callbackUrl' => 'getCallbackUrl',
        'metadata' => 'getMetadata',
        'splitCode' => 'getSplitCode',
        'subaccount' => 'getSubaccount',
        'transactionCharge' => 'getTransactionCharge',
        'bearer' => 'getBearer',
        'expireAction' => 'getExpireAction',
        'expireAfterDays' => 'getExpireAfterDays'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CURRENCY_ZAR = 'ZAR';
    public const BEARER_ACCOUNT = 'account';
    public const BEARER_SUBACCOUNT = 'subaccount';
    public const EXPIRE_ACTION_CAPTURE = 'capture';
    public const EXPIRE_ACTION_RELEASE = 'release';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCurrencyAllowableValues()
    {
        return [
            self::CURRENCY_ZAR,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBearerAllowableValues()
    {
        return [
            self::BEARER_ACCOUNT,
            self::BEARER_SUBACCOUNT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getExpireActionAllowableValues()
    {
        return [
            self::EXPIRE_ACTION_CAPTURE,
            self::EXPIRE_ACTION_RELEASE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('reference', $data ?? [], null);
        $this->setIfExists('callbackUrl', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('splitCode', $data ?? [], null);
        $this->setIfExists('subaccount', $data ?? [], null);
        $this->setIfExists('transactionCharge', $data ?? [], null);
        $this->setIfExists('bearer', $data ?? [], null);
        $this->setIfExists('expireAction', $data ?? [], null);
        $this->setIfExists('expireAfterDays', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        $allowedValues = $this->getCurrencyAllowableValues();
        if (!is_null($this->container['currency']) && !in_array($this->container['currency'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'currency', must be one of '%s'",
                $this->container['currency'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getBearerAllowableValues();
        if (!is_null($this->container['bearer']) && !in_array($this->container['bearer'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'bearer', must be one of '%s'",
                $this->container['bearer'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getExpireActionAllowableValues();
        if (!is_null($this->container['expireAction']) && !in_array($this->container['expireAction'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'expireAction', must be one of '%s'",
                $this->container['expireAction'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['expireAfterDays']) && ($this->container['expireAfterDays'] > 30)) {
            $invalidProperties[] = "invalid value for 'expireAfterDays', must be smaller than or equal to 30.";
        }

        if (!is_null($this->container['expireAfterDays']) && ($this->container['expireAfterDays'] < 1)) {
            $invalidProperties[] = "invalid value for 'expireAfterDays', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets amount
     *
     * @return string
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param string $amount Amount should be in the subunit of the supported currency
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email Customer's email address
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency Only ZAR is supported for now
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $allowedValues = $this->getCurrencyAllowableValues();
        if (!in_array($currency, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'currency', must be one of '%s'",
                    $currency,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string|null
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string|null $reference Unique transaction reference. Only -, ., = and alphanumeric characters allowed.
     *
     * @return self
     */
    public function setReference($reference)
    {
        if (is_null($reference)) {
            throw new \InvalidArgumentException('non-nullable reference cannot be null');
        }
        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets callbackUrl
     *
     * @return string|null
     */
    public function getCallbackUrl()
    {
        return $this->container['callbackUrl'];
    }

    /**
     * Sets callbackUrl
     *
     * @param string|null $callbackUrl Fully qualified url, e.g. https://example.com/ . Use this to override the callback url provided on the dashboard for this transaction
     *
     * @return self
     */
    public function setCallbackUrl($callbackUrl)
    {
        if (is_null($callbackUrl)) {
            throw new \InvalidArgumentException('non-nullable callbackUrl cannot be null');
        }
        $this->container['callbackUrl'] = $callbackUrl;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return \Alexasomba\Paystack\Model\PreAuthorizationInitializeMetadata|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param \Alexasomba\Paystack\Model\PreAuthorizationInitializeMetadata|null $metadata metadata
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets splitCode
     *
     * @return string|null
     */
    public function getSplitCode()
    {
        return $this->container['splitCode'];
    }

    /**
     * Sets splitCode
     *
     * @param string|null $splitCode The split code of the transaction split. e.g. SPL_98WF13Eb3w
     *
     * @return self
     */
    public function setSplitCode($splitCode)
    {
        if (is_null($splitCode)) {
            throw new \InvalidArgumentException('non-nullable splitCode cannot be null');
        }
        $this->container['splitCode'] = $splitCode;

        return $this;
    }

    /**
     * Gets subaccount
     *
     * @return string|null
     */
    public function getSubaccount()
    {
        return $this->container['subaccount'];
    }

    /**
     * Sets subaccount
     *
     * @param string|null $subaccount The code for the subaccount that owns the payment. e.g. ACCT_8f4s1eq7ml6rlzj
     *
     * @return self
     */
    public function setSubaccount($subaccount)
    {
        if (is_null($subaccount)) {
            throw new \InvalidArgumentException('non-nullable subaccount cannot be null');
        }
        $this->container['subaccount'] = $subaccount;

        return $this;
    }

    /**
     * Gets transactionCharge
     *
     * @return int|null
     */
    public function getTransactionCharge()
    {
        return $this->container['transactionCharge'];
    }

    /**
     * Sets transactionCharge
     *
     * @param int|null $transactionCharge An amount used to override the split configuration for a single split payment. If set, the amount specified goes to the main account regardless of the split configuration.
     *
     * @return self
     */
    public function setTransactionCharge($transactionCharge)
    {
        if (is_null($transactionCharge)) {
            throw new \InvalidArgumentException('non-nullable transactionCharge cannot be null');
        }
        $this->container['transactionCharge'] = $transactionCharge;

        return $this;
    }

    /**
     * Gets bearer
     *
     * @return string|null
     */
    public function getBearer()
    {
        return $this->container['bearer'];
    }

    /**
     * Sets bearer
     *
     * @param string|null $bearer Specifies who will pay the Paystack transaction charges for this transaction. Either account or subaccount (defaults to account).
     *
     * @return self
     */
    public function setBearer($bearer)
    {
        if (is_null($bearer)) {
            throw new \InvalidArgumentException('non-nullable bearer cannot be null');
        }
        $allowedValues = $this->getBearerAllowableValues();
        if (!in_array($bearer, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'bearer', must be one of '%s'",
                    $bearer,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['bearer'] = $bearer;

        return $this;
    }

    /**
     * Gets expireAction
     *
     * @return string|null
     */
    public function getExpireAction()
    {
        return $this->container['expireAction'];
    }

    /**
     * Sets expireAction
     *
     * @param string|null $expireAction Specify the action to take on the expiry date. It’s either capture or release. Defaults to release.
     *
     * @return self
     */
    public function setExpireAction($expireAction)
    {
        if (is_null($expireAction)) {
            throw new \InvalidArgumentException('non-nullable expireAction cannot be null');
        }
        $allowedValues = $this->getExpireActionAllowableValues();
        if (!in_array($expireAction, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'expireAction', must be one of '%s'",
                    $expireAction,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['expireAction'] = $expireAction;

        return $this;
    }

    /**
     * Gets expireAfterDays
     *
     * @return int|null
     */
    public function getExpireAfterDays()
    {
        return $this->container['expireAfterDays'];
    }

    /**
     * Sets expireAfterDays
     *
     * @param int|null $expireAfterDays The number of days until the expire_action is executed. The minimum is 1 day and maximum 30 days. Defaults to 5 days.
     *
     * @return self
     */
    public function setExpireAfterDays($expireAfterDays)
    {
        if (is_null($expireAfterDays)) {
            throw new \InvalidArgumentException('non-nullable expireAfterDays cannot be null');
        }

        if (($expireAfterDays > 30)) {
            throw new \InvalidArgumentException('invalid value for $expireAfterDays when calling PreAuthorizationInitialize., must be smaller than or equal to 30.');
        }
        if (($expireAfterDays < 1)) {
            throw new \InvalidArgumentException('invalid value for $expireAfterDays when calling PreAuthorizationInitialize., must be bigger than or equal to 1.');
        }

        $this->container['expireAfterDays'] = $expireAfterDays;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


