<?php
/**
 * TransferCreateResponseData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Alexasomba\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paystack
 *
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: techsupport@paystack.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Alexasomba\Paystack\Model;

use \ArrayAccess;
use \Alexasomba\Paystack\ObjectSerializer;

/**
 * TransferCreateResponseData Class Doc Comment
 *
 * @category Class
 * @package  Alexasomba\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TransferCreateResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TransferCreateResponse_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'transfersessionid' => 'mixed[]',
        'transfertrials' => 'mixed[]',
        'domain' => 'string',
        'amount' => 'int',
        'currency' => 'string',
        'reference' => 'string',
        'source' => 'string',
        'sourceDetails' => 'mixed',
        'reason' => 'string',
        'status' => 'string',
        'failures' => 'mixed',
        'transferCode' => 'string',
        'titanCode' => 'mixed',
        'transferredAt' => 'mixed',
        'id' => 'int',
        'integration' => 'int',
        'request' => 'int',
        'recipient' => 'int',
        'createdAt' => 'string',
        'updatedAt' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'transfersessionid' => null,
        'transfertrials' => null,
        'domain' => null,
        'amount' => null,
        'currency' => null,
        'reference' => null,
        'source' => null,
        'sourceDetails' => null,
        'reason' => null,
        'status' => null,
        'failures' => null,
        'transferCode' => null,
        'titanCode' => null,
        'transferredAt' => null,
        'id' => null,
        'integration' => null,
        'request' => null,
        'recipient' => null,
        'createdAt' => null,
        'updatedAt' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'transfersessionid' => false,
        'transfertrials' => false,
        'domain' => false,
        'amount' => false,
        'currency' => false,
        'reference' => false,
        'source' => false,
        'sourceDetails' => true,
        'reason' => false,
        'status' => false,
        'failures' => true,
        'transferCode' => false,
        'titanCode' => true,
        'transferredAt' => true,
        'id' => false,
        'integration' => false,
        'request' => false,
        'recipient' => false,
        'createdAt' => false,
        'updatedAt' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'transfersessionid' => 'transfersessionid',
        'transfertrials' => 'transfertrials',
        'domain' => 'domain',
        'amount' => 'amount',
        'currency' => 'currency',
        'reference' => 'reference',
        'source' => 'source',
        'sourceDetails' => 'source_details',
        'reason' => 'reason',
        'status' => 'status',
        'failures' => 'failures',
        'transferCode' => 'transfer_code',
        'titanCode' => 'titan_code',
        'transferredAt' => 'transferred_at',
        'id' => 'id',
        'integration' => 'integration',
        'request' => 'request',
        'recipient' => 'recipient',
        'createdAt' => 'createdAt',
        'updatedAt' => 'updatedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'transfersessionid' => 'setTransfersessionid',
        'transfertrials' => 'setTransfertrials',
        'domain' => 'setDomain',
        'amount' => 'setAmount',
        'currency' => 'setCurrency',
        'reference' => 'setReference',
        'source' => 'setSource',
        'sourceDetails' => 'setSourceDetails',
        'reason' => 'setReason',
        'status' => 'setStatus',
        'failures' => 'setFailures',
        'transferCode' => 'setTransferCode',
        'titanCode' => 'setTitanCode',
        'transferredAt' => 'setTransferredAt',
        'id' => 'setId',
        'integration' => 'setIntegration',
        'request' => 'setRequest',
        'recipient' => 'setRecipient',
        'createdAt' => 'setCreatedAt',
        'updatedAt' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'transfersessionid' => 'getTransfersessionid',
        'transfertrials' => 'getTransfertrials',
        'domain' => 'getDomain',
        'amount' => 'getAmount',
        'currency' => 'getCurrency',
        'reference' => 'getReference',
        'source' => 'getSource',
        'sourceDetails' => 'getSourceDetails',
        'reason' => 'getReason',
        'status' => 'getStatus',
        'failures' => 'getFailures',
        'transferCode' => 'getTransferCode',
        'titanCode' => 'getTitanCode',
        'transferredAt' => 'getTransferredAt',
        'id' => 'getId',
        'integration' => 'getIntegration',
        'request' => 'getRequest',
        'recipient' => 'getRecipient',
        'createdAt' => 'getCreatedAt',
        'updatedAt' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('transfersessionid', $data ?? [], null);
        $this->setIfExists('transfertrials', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('reference', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('sourceDetails', $data ?? [], null);
        $this->setIfExists('reason', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('failures', $data ?? [], null);
        $this->setIfExists('transferCode', $data ?? [], null);
        $this->setIfExists('titanCode', $data ?? [], null);
        $this->setIfExists('transferredAt', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('integration', $data ?? [], null);
        $this->setIfExists('request', $data ?? [], null);
        $this->setIfExists('recipient', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['transfersessionid'] === null) {
            $invalidProperties[] = "'transfersessionid' can't be null";
        }
        if ($this->container['transfertrials'] === null) {
            $invalidProperties[] = "'transfertrials' can't be null";
        }
        if ($this->container['domain'] === null) {
            $invalidProperties[] = "'domain' can't be null";
        }
        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        if ($this->container['reference'] === null) {
            $invalidProperties[] = "'reference' can't be null";
        }
        if ($this->container['source'] === null) {
            $invalidProperties[] = "'source' can't be null";
        }
        if ($this->container['sourceDetails'] === null && !$this->isNullableSetToNull('sourceDetails')) {
            $invalidProperties[] = "'sourceDetails' can't be null";
        }
        if ($this->container['reason'] === null) {
            $invalidProperties[] = "'reason' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['failures'] === null && !$this->isNullableSetToNull('failures')) {
            $invalidProperties[] = "'failures' can't be null";
        }
        if ($this->container['transferCode'] === null) {
            $invalidProperties[] = "'transferCode' can't be null";
        }
        if ($this->container['titanCode'] === null && !$this->isNullableSetToNull('titanCode')) {
            $invalidProperties[] = "'titanCode' can't be null";
        }
        if ($this->container['transferredAt'] === null && !$this->isNullableSetToNull('transferredAt')) {
            $invalidProperties[] = "'transferredAt' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['integration'] === null) {
            $invalidProperties[] = "'integration' can't be null";
        }
        if ($this->container['request'] === null) {
            $invalidProperties[] = "'request' can't be null";
        }
        if ($this->container['recipient'] === null) {
            $invalidProperties[] = "'recipient' can't be null";
        }
        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['updatedAt'] === null) {
            $invalidProperties[] = "'updatedAt' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets transfersessionid
     *
     * @return mixed[]
     */
    public function getTransfersessionid()
    {
        return $this->container['transfersessionid'];
    }

    /**
     * Sets transfersessionid
     *
     * @param mixed[] $transfersessionid transfersessionid
     *
     * @return self
     */
    public function setTransfersessionid($transfersessionid)
    {
        if (is_null($transfersessionid)) {
            throw new \InvalidArgumentException('non-nullable transfersessionid cannot be null');
        }
        $this->container['transfersessionid'] = $transfersessionid;

        return $this;
    }

    /**
     * Gets transfertrials
     *
     * @return mixed[]
     */
    public function getTransfertrials()
    {
        return $this->container['transfertrials'];
    }

    /**
     * Sets transfertrials
     *
     * @param mixed[] $transfertrials transfertrials
     *
     * @return self
     */
    public function setTransfertrials($transfertrials)
    {
        if (is_null($transfertrials)) {
            throw new \InvalidArgumentException('non-nullable transfertrials cannot be null');
        }
        $this->container['transfertrials'] = $transfertrials;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string $domain domain
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            throw new \InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return int
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string $reference reference
     *
     * @return self
     */
    public function setReference($reference)
    {
        if (is_null($reference)) {
            throw new \InvalidArgumentException('non-nullable reference cannot be null');
        }
        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets sourceDetails
     *
     * @return mixed|null
     */
    public function getSourceDetails()
    {
        return $this->container['sourceDetails'];
    }

    /**
     * Sets sourceDetails
     *
     * @param mixed|null $sourceDetails sourceDetails
     *
     * @return self
     */
    public function setSourceDetails($sourceDetails)
    {
        if (is_null($sourceDetails)) {
            array_push($this->openAPINullablesSetToNull, 'sourceDetails');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sourceDetails', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sourceDetails'] = $sourceDetails;

        return $this;
    }

    /**
     * Gets reason
     *
     * @return string
     */
    public function getReason()
    {
        return $this->container['reason'];
    }

    /**
     * Sets reason
     *
     * @param string $reason reason
     *
     * @return self
     */
    public function setReason($reason)
    {
        if (is_null($reason)) {
            throw new \InvalidArgumentException('non-nullable reason cannot be null');
        }
        $this->container['reason'] = $reason;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets failures
     *
     * @return mixed|null
     */
    public function getFailures()
    {
        return $this->container['failures'];
    }

    /**
     * Sets failures
     *
     * @param mixed|null $failures failures
     *
     * @return self
     */
    public function setFailures($failures)
    {
        if (is_null($failures)) {
            array_push($this->openAPINullablesSetToNull, 'failures');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('failures', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['failures'] = $failures;

        return $this;
    }

    /**
     * Gets transferCode
     *
     * @return string
     */
    public function getTransferCode()
    {
        return $this->container['transferCode'];
    }

    /**
     * Sets transferCode
     *
     * @param string $transferCode transferCode
     *
     * @return self
     */
    public function setTransferCode($transferCode)
    {
        if (is_null($transferCode)) {
            throw new \InvalidArgumentException('non-nullable transferCode cannot be null');
        }
        $this->container['transferCode'] = $transferCode;

        return $this;
    }

    /**
     * Gets titanCode
     *
     * @return mixed|null
     */
    public function getTitanCode()
    {
        return $this->container['titanCode'];
    }

    /**
     * Sets titanCode
     *
     * @param mixed|null $titanCode titanCode
     *
     * @return self
     */
    public function setTitanCode($titanCode)
    {
        if (is_null($titanCode)) {
            array_push($this->openAPINullablesSetToNull, 'titanCode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('titanCode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['titanCode'] = $titanCode;

        return $this;
    }

    /**
     * Gets transferredAt
     *
     * @return mixed|null
     */
    public function getTransferredAt()
    {
        return $this->container['transferredAt'];
    }

    /**
     * Sets transferredAt
     *
     * @param mixed|null $transferredAt transferredAt
     *
     * @return self
     */
    public function setTransferredAt($transferredAt)
    {
        if (is_null($transferredAt)) {
            array_push($this->openAPINullablesSetToNull, 'transferredAt');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('transferredAt', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['transferredAt'] = $transferredAt;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets integration
     *
     * @return int
     */
    public function getIntegration()
    {
        return $this->container['integration'];
    }

    /**
     * Sets integration
     *
     * @param int $integration integration
     *
     * @return self
     */
    public function setIntegration($integration)
    {
        if (is_null($integration)) {
            throw new \InvalidArgumentException('non-nullable integration cannot be null');
        }
        $this->container['integration'] = $integration;

        return $this;
    }

    /**
     * Gets request
     *
     * @return int
     */
    public function getRequest()
    {
        return $this->container['request'];
    }

    /**
     * Sets request
     *
     * @param int $request request
     *
     * @return self
     */
    public function setRequest($request)
    {
        if (is_null($request)) {
            throw new \InvalidArgumentException('non-nullable request cannot be null');
        }
        $this->container['request'] = $request;

        return $this;
    }

    /**
     * Gets recipient
     *
     * @return int
     */
    public function getRecipient()
    {
        return $this->container['recipient'];
    }

    /**
     * Sets recipient
     *
     * @param int $recipient recipient
     *
     * @return self
     */
    public function setRecipient($recipient)
    {
        if (is_null($recipient)) {
            throw new \InvalidArgumentException('non-nullable recipient cannot be null');
        }
        $this->container['recipient'] = $recipient;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param string $createdAt createdAt
     *
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        if (is_null($createdAt)) {
            throw new \InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param string $updatedAt updatedAt
     *
     * @return self
     */
    public function setUpdatedAt($updatedAt)
    {
        if (is_null($updatedAt)) {
            throw new \InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


