<?php
/**
 * MiscellaneousListCountriesResponseArrayRelationshipsCurrencySupportedCurrenciesUSDBankTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Alexasomba\\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paystack
 *
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: techsupport@paystack.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Alexasomba\\Paystack\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MiscellaneousListCountriesResponseArrayRelationshipsCurrencySupportedCurrenciesUSDBankTest Class Doc Comment
 *
 * @category    Class
 * @description MiscellaneousListCountriesResponseArrayRelationshipsCurrencySupportedCurrenciesUSDBank
 * @package     Alexasomba\\Paystack
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MiscellaneousListCountriesResponseArrayRelationshipsCurrencySupportedCurrenciesUSDBankTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MiscellaneousListCountriesResponseArrayRelationshipsCurrencySupportedCurrenciesUSDBank"
     */
    public function testMiscellaneousListCountriesResponseArrayRelationshipsCurrencySupportedCurrenciesUSDBank()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bank_type"
     */
    public function testPropertyBankType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "required_fields"
     */
    public function testPropertyRequiredFields()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "branch_code"
     */
    public function testPropertyBranchCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "branch_code_type"
     */
    public function testPropertyBranchCodeType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_name"
     */
    public function testPropertyAccountName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_verification_required"
     */
    public function testPropertyAccountVerificationRequired()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_number_label"
     */
    public function testPropertyAccountNumberLabel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_number_pattern"
     */
    public function testPropertyAccountNumberPattern()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "documents"
     */
    public function testPropertyDocuments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "notices"
     */
    public function testPropertyNotices()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
