<?php
/**
 * CustomerApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Alexasomba\\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paystack
 *
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: techsupport@paystack.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Alexasomba\\Paystack\Test\Api;

use \Alexasomba\\Paystack\Configuration;
use \Alexasomba\\Paystack\ApiException;
use \Alexasomba\\Paystack\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Alexasomba\\Paystack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for customerCreate
     *
     * Create Customer.
     *
     */
    public function testCustomerCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerDeactivateAuthorization
     *
     * Deactivate Authorization.
     *
     */
    public function testCustomerDeactivateAuthorization()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerDirectDebitActivationCharge
     *
     * Direct Debit Activation Charge.
     *
     */
    public function testCustomerDirectDebitActivationCharge()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerFetch
     *
     * Fetch Customer.
     *
     */
    public function testCustomerFetch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerFetchMandateAuthorizations
     *
     * Fetch Mandate Authorizations.
     *
     */
    public function testCustomerFetchMandateAuthorizations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerInitializeAuthorization
     *
     * Initialize Authorization.
     *
     */
    public function testCustomerInitializeAuthorization()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerInitializeDirectDebit
     *
     * Initialize Direct Debit.
     *
     */
    public function testCustomerInitializeDirectDebit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerList
     *
     * List Customers.
     *
     */
    public function testCustomerList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerRiskAction
     *
     * Set Risk Action.
     *
     */
    public function testCustomerRiskAction()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerUpdate
     *
     * Update Customer.
     *
     */
    public function testCustomerUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerValidate
     *
     * Validate Customer.
     *
     */
    public function testCustomerValidate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerVerifyAuthorization
     *
     * Verify Authorization.
     *
     */
    public function testCustomerVerifyAuthorization()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
